// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	kiwi "github.com/skynet2/kiwi-tcms-mcp/pkg/kiwi"
)

// MockKiwiClient is a mock of KiwiClient interface.
type MockKiwiClient struct {
	ctrl     *gomock.Controller
	recorder *MockKiwiClientMockRecorder
}

// MockKiwiClientMockRecorder is the mock recorder for MockKiwiClient.
type MockKiwiClientMockRecorder struct {
	mock *MockKiwiClient
}

// NewMockKiwiClient creates a new mock instance.
func NewMockKiwiClient(ctrl *gomock.Controller) *MockKiwiClient {
	mock := &MockKiwiClient{ctrl: ctrl}
	mock.recorder = &MockKiwiClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKiwiClient) EXPECT() *MockKiwiClientMockRecorder {
	return m.recorder
}

// CategoryFilter mocks base method.
func (m *MockKiwiClient) CategoryFilter(ctx context.Context, q map[string]any) ([]kiwi.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CategoryFilter", ctx, q)
	ret0, _ := ret[0].([]kiwi.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CategoryFilter indicates an expected call of CategoryFilter.
func (mr *MockKiwiClientMockRecorder) CategoryFilter(ctx, q interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CategoryFilter", reflect.TypeOf((*MockKiwiClient)(nil).CategoryFilter), ctx, q)
}

// ComponentFilter mocks base method.
func (m *MockKiwiClient) ComponentFilter(ctx context.Context, q map[string]any) ([]kiwi.Component, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComponentFilter", ctx, q)
	ret0, _ := ret[0].([]kiwi.Component)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ComponentFilter indicates an expected call of ComponentFilter.
func (mr *MockKiwiClientMockRecorder) ComponentFilter(ctx, q interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComponentFilter", reflect.TypeOf((*MockKiwiClient)(nil).ComponentFilter), ctx, q)
}

// PriorityFilter mocks base method.
func (m *MockKiwiClient) PriorityFilter(ctx context.Context, q map[string]any) ([]kiwi.Priority, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PriorityFilter", ctx, q)
	ret0, _ := ret[0].([]kiwi.Priority)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PriorityFilter indicates an expected call of PriorityFilter.
func (mr *MockKiwiClientMockRecorder) PriorityFilter(ctx, q interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PriorityFilter", reflect.TypeOf((*MockKiwiClient)(nil).PriorityFilter), ctx, q)
}

// ProductFilter mocks base method.
func (m *MockKiwiClient) ProductFilter(ctx context.Context, q map[string]any) ([]kiwi.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProductFilter", ctx, q)
	ret0, _ := ret[0].([]kiwi.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProductFilter indicates an expected call of ProductFilter.
func (mr *MockKiwiClientMockRecorder) ProductFilter(ctx, q interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProductFilter", reflect.TypeOf((*MockKiwiClient)(nil).ProductFilter), ctx, q)
}

// TagFilter mocks base method.
func (m *MockKiwiClient) TagFilter(ctx context.Context, q map[string]any) ([]kiwi.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TagFilter", ctx, q)
	ret0, _ := ret[0].([]kiwi.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TagFilter indicates an expected call of TagFilter.
func (mr *MockKiwiClientMockRecorder) TagFilter(ctx, q interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagFilter", reflect.TypeOf((*MockKiwiClient)(nil).TagFilter), ctx, q)
}

// TestCaseAddComment mocks base method.
func (m *MockKiwiClient) TestCaseAddComment(ctx context.Context, caseID int64, comment string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestCaseAddComment", ctx, caseID, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// TestCaseAddComment indicates an expected call of TestCaseAddComment.
func (mr *MockKiwiClientMockRecorder) TestCaseAddComment(ctx, caseID, comment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestCaseAddComment", reflect.TypeOf((*MockKiwiClient)(nil).TestCaseAddComment), ctx, caseID, comment)
}

// TestCaseAddComponent mocks base method.
func (m *MockKiwiClient) TestCaseAddComponent(ctx context.Context, caseID int64, component string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestCaseAddComponent", ctx, caseID, component)
	ret0, _ := ret[0].(error)
	return ret0
}

// TestCaseAddComponent indicates an expected call of TestCaseAddComponent.
func (mr *MockKiwiClientMockRecorder) TestCaseAddComponent(ctx, caseID, component interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestCaseAddComponent", reflect.TypeOf((*MockKiwiClient)(nil).TestCaseAddComponent), ctx, caseID, component)
}

// TestCaseAddLink mocks base method.
func (m *MockKiwiClient) TestCaseAddLink(ctx context.Context, link map[string]any) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestCaseAddLink", ctx, link)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TestCaseAddLink indicates an expected call of TestCaseAddLink.
func (mr *MockKiwiClientMockRecorder) TestCaseAddLink(ctx, link interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestCaseAddLink", reflect.TypeOf((*MockKiwiClient)(nil).TestCaseAddLink), ctx, link)
}

// TestCaseAddProperty mocks base method.
func (m *MockKiwiClient) TestCaseAddProperty(ctx context.Context, caseID int64, name, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestCaseAddProperty", ctx, caseID, name, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// TestCaseAddProperty indicates an expected call of TestCaseAddProperty.
func (mr *MockKiwiClientMockRecorder) TestCaseAddProperty(ctx, caseID, name, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestCaseAddProperty", reflect.TypeOf((*MockKiwiClient)(nil).TestCaseAddProperty), ctx, caseID, name, value)
}

// TestCaseAddTag mocks base method.
func (m *MockKiwiClient) TestCaseAddTag(ctx context.Context, caseID int64, tag string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestCaseAddTag", ctx, caseID, tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// TestCaseAddTag indicates an expected call of TestCaseAddTag.
func (mr *MockKiwiClientMockRecorder) TestCaseAddTag(ctx, caseID, tag interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestCaseAddTag", reflect.TypeOf((*MockKiwiClient)(nil).TestCaseAddTag), ctx, caseID, tag)
}

// TestCaseCreate mocks base method.
func (m *MockKiwiClient) TestCaseCreate(ctx context.Context, in kiwi.TestCaseCreateInput) (kiwi.TestCase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestCaseCreate", ctx, in)
	ret0, _ := ret[0].(kiwi.TestCase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TestCaseCreate indicates an expected call of TestCaseCreate.
func (mr *MockKiwiClientMockRecorder) TestCaseCreate(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestCaseCreate", reflect.TypeOf((*MockKiwiClient)(nil).TestCaseCreate), ctx, in)
}

// TestCaseFilter mocks base method.
func (m *MockKiwiClient) TestCaseFilter(ctx context.Context, q map[string]any) ([]kiwi.TestCase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestCaseFilter", ctx, q)
	ret0, _ := ret[0].([]kiwi.TestCase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TestCaseFilter indicates an expected call of TestCaseFilter.
func (mr *MockKiwiClientMockRecorder) TestCaseFilter(ctx, q interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestCaseFilter", reflect.TypeOf((*MockKiwiClient)(nil).TestCaseFilter), ctx, q)
}

// TestCaseRemove mocks base method.
func (m *MockKiwiClient) TestCaseRemove(ctx context.Context, q map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestCaseRemove", ctx, q)
	ret0, _ := ret[0].(error)
	return ret0
}

// TestCaseRemove indicates an expected call of TestCaseRemove.
func (mr *MockKiwiClientMockRecorder) TestCaseRemove(ctx, q interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestCaseRemove", reflect.TypeOf((*MockKiwiClient)(nil).TestCaseRemove), ctx, q)
}

// TestCaseRemoveComponent mocks base method.
func (m *MockKiwiClient) TestCaseRemoveComponent(ctx context.Context, caseID int64, component int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestCaseRemoveComponent", ctx, caseID, component)
	ret0, _ := ret[0].(error)
	return ret0
}

// TestCaseRemoveComponent indicates an expected call of TestCaseRemoveComponent.
func (mr *MockKiwiClientMockRecorder) TestCaseRemoveComponent(ctx, caseID, component interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestCaseRemoveComponent", reflect.TypeOf((*MockKiwiClient)(nil).TestCaseRemoveComponent), ctx, caseID, component)
}

// TestCaseRemoveLink mocks base method.
func (m *MockKiwiClient) TestCaseRemoveLink(ctx context.Context, q map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestCaseRemoveLink", ctx, q)
	ret0, _ := ret[0].(error)
	return ret0
}

// TestCaseRemoveLink indicates an expected call of TestCaseRemoveLink.
func (mr *MockKiwiClientMockRecorder) TestCaseRemoveLink(ctx, q interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestCaseRemoveLink", reflect.TypeOf((*MockKiwiClient)(nil).TestCaseRemoveLink), ctx, q)
}

// TestCaseRemoveProperty mocks base method.
func (m *MockKiwiClient) TestCaseRemoveProperty(ctx context.Context, q map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestCaseRemoveProperty", ctx, q)
	ret0, _ := ret[0].(error)
	return ret0
}

// TestCaseRemoveProperty indicates an expected call of TestCaseRemoveProperty.
func (mr *MockKiwiClientMockRecorder) TestCaseRemoveProperty(ctx, q interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestCaseRemoveProperty", reflect.TypeOf((*MockKiwiClient)(nil).TestCaseRemoveProperty), ctx, q)
}

// TestCaseRemoveTag mocks base method.
func (m *MockKiwiClient) TestCaseRemoveTag(ctx context.Context, caseID int64, tag string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestCaseRemoveTag", ctx, caseID, tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// TestCaseRemoveTag indicates an expected call of TestCaseRemoveTag.
func (mr *MockKiwiClientMockRecorder) TestCaseRemoveTag(ctx, caseID, tag interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestCaseRemoveTag", reflect.TypeOf((*MockKiwiClient)(nil).TestCaseRemoveTag), ctx, caseID, tag)
}

// TestCaseStatusFilter mocks base method.
func (m *MockKiwiClient) TestCaseStatusFilter(ctx context.Context, q map[string]any) ([]kiwi.TestCaseStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestCaseStatusFilter", ctx, q)
	ret0, _ := ret[0].([]kiwi.TestCaseStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TestCaseStatusFilter indicates an expected call of TestCaseStatusFilter.
func (mr *MockKiwiClientMockRecorder) TestCaseStatusFilter(ctx, q interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestCaseStatusFilter", reflect.TypeOf((*MockKiwiClient)(nil).TestCaseStatusFilter), ctx, q)
}

// TestCaseUpdate mocks base method.
func (m *MockKiwiClient) TestCaseUpdate(ctx context.Context, id int64, patch map[string]any) (kiwi.TestCase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestCaseUpdate", ctx, id, patch)
	ret0, _ := ret[0].(kiwi.TestCase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TestCaseUpdate indicates an expected call of TestCaseUpdate.
func (mr *MockKiwiClientMockRecorder) TestCaseUpdate(ctx, id, patch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestCaseUpdate", reflect.TypeOf((*MockKiwiClient)(nil).TestCaseUpdate), ctx, id, patch)
}

// UserFilter mocks base method.
func (m *MockKiwiClient) UserFilter(ctx context.Context, q map[string]any) ([]kiwi.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserFilter", ctx, q)
	ret0, _ := ret[0].([]kiwi.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserFilter indicates an expected call of UserFilter.
func (mr *MockKiwiClientMockRecorder) UserFilter(ctx, q interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserFilter", reflect.TypeOf((*MockKiwiClient)(nil).UserFilter), ctx, q)
}
